STORES = [
    "A Class Hair Studio",
    "Aerie",
    "Aeropostale",
    "American Eagle",
    "a t and t",
    "Atlantic Union Bank",
    "Auntie Anne's",
    "Banter",
    "Bath and Body Works",
    "Beatutides Hair and Beauty Supply Store",
    "Belk",
    "Bj's Wholesale Club",
    "Bleacher Bums",
    "Chris Cross Cafe",
    "Bam! Books a Million",
    "Boost Mobile",
    "Box Lunch",
    "Branhams Candies",
    "Bubble House",
    "Cielt lindo",
    "Cinnabon",
    "Claire's",
    "Crumble Cookies",
    "Dairy Queen",
    "Dick's Sporting Goods",
    "Dr Phone Repair",
    "ATM",
    "Empire Jewelry and Diamonds",
    "Europe Nails",
    "Dick's Sporting Goods",
    "Target",
    "Best Buy",
    "Food Court",
    "Apple Store",
    "Macy's",
    "GameStop",
    "Restrooms",
]